create table "public"."cafes" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."cafes" enable row level security;

create table "public"."products" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."products" enable row level security;

CREATE UNIQUE INDEX cafes_pkey ON public.cafes USING btree (id);

CREATE UNIQUE INDEX products_pkey ON public.products USING btree (id);

alter table "public"."cafes" add constraint "cafes_pkey" PRIMARY KEY using index "cafes_pkey";

alter table "public"."products" add constraint "products_pkey" PRIMARY KEY using index "products_pkey";

grant delete on table "public"."cafes" to "anon";

grant insert on table "public"."cafes" to "anon";

grant references on table "public"."cafes" to "anon";

grant select on table "public"."cafes" to "anon";

grant trigger on table "public"."cafes" to "anon";

grant truncate on table "public"."cafes" to "anon";

grant update on table "public"."cafes" to "anon";

grant delete on table "public"."cafes" to "authenticated";

grant insert on table "public"."cafes" to "authenticated";

grant references on table "public"."cafes" to "authenticated";

grant select on table "public"."cafes" to "authenticated";

grant trigger on table "public"."cafes" to "authenticated";

grant truncate on table "public"."cafes" to "authenticated";

grant update on table "public"."cafes" to "authenticated";

grant delete on table "public"."cafes" to "service_role";

grant insert on table "public"."cafes" to "service_role";

grant references on table "public"."cafes" to "service_role";

grant select on table "public"."cafes" to "service_role";

grant trigger on table "public"."cafes" to "service_role";

grant truncate on table "public"."cafes" to "service_role";

grant update on table "public"."cafes" to "service_role";

grant delete on table "public"."products" to "anon";

grant insert on table "public"."products" to "anon";

grant references on table "public"."products" to "anon";

grant select on table "public"."products" to "anon";

grant trigger on table "public"."products" to "anon";

grant truncate on table "public"."products" to "anon";

grant update on table "public"."products" to "anon";

grant delete on table "public"."products" to "authenticated";

grant insert on table "public"."products" to "authenticated";

grant references on table "public"."products" to "authenticated";

grant select on table "public"."products" to "authenticated";

grant trigger on table "public"."products" to "authenticated";

grant truncate on table "public"."products" to "authenticated";

grant update on table "public"."products" to "authenticated";

grant delete on table "public"."products" to "service_role";

grant insert on table "public"."products" to "service_role";

grant references on table "public"."products" to "service_role";

grant select on table "public"."products" to "service_role";

grant trigger on table "public"."products" to "service_role";

grant truncate on table "public"."products" to "service_role";

grant update on table "public"."products" to "service_role";



