create table "public"."testo" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."testo" enable row level security;

CREATE UNIQUE INDEX testo_pkey ON public.testo USING btree (id);

alter table "public"."testo" add constraint "testo_pkey" PRIMARY KEY using index "testo_pkey";

grant delete on table "public"."testo" to "anon";

grant insert on table "public"."testo" to "anon";

grant references on table "public"."testo" to "anon";

grant select on table "public"."testo" to "anon";

grant trigger on table "public"."testo" to "anon";

grant truncate on table "public"."testo" to "anon";

grant update on table "public"."testo" to "anon";

grant delete on table "public"."testo" to "authenticated";

grant insert on table "public"."testo" to "authenticated";

grant references on table "public"."testo" to "authenticated";

grant select on table "public"."testo" to "authenticated";

grant trigger on table "public"."testo" to "authenticated";

grant truncate on table "public"."testo" to "authenticated";

grant update on table "public"."testo" to "authenticated";

grant delete on table "public"."testo" to "service_role";

grant insert on table "public"."testo" to "service_role";

grant references on table "public"."testo" to "service_role";

grant select on table "public"."testo" to "service_role";

grant trigger on table "public"."testo" to "service_role";

grant truncate on table "public"."testo" to "service_role";

grant update on table "public"."testo" to "service_role";



